name: Run Python Checks on Changed Files
on:
  pull_request:
    paths:
      - '**/*.py'

jobs:
  run-python-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get list of changed Python files
        id: changed_files
        run: |
          git fetch origin master
          changed_files=$(git diff --name-only origin/master...HEAD -- '*.py')
          echo "files=$changed_files" >> $GITHUB_ENV

      - name: Run Python Checks Action
        uses: ./.github/actions/python-checks
        with:
          files: ${{ env.files }}